BEGIN;

CREATE TABLE IF NOT EXISTS public."Utilisateurs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Utilisateurs" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Utilisateurs_Nom" UNIQUE ("Nom")
);

CREATE TABLE IF NOT EXISTS public."Listes"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "UtilisateurId" integer NOT NULL,
    "DateCreation" timestamp without time zone NOT NULL DEFAULT now(),
    "EstPublique" boolean NOT NULL DEFAULT true,
    "DiscordServerUrl" text COLLATE pg_catalog."default",
    "RawFootageMode" integer NOT NULL DEFAULT 0,
    "RawFootageTopStart" integer,
    CONSTRAINT "PK_Listes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."MembresListe"
(
    "ListeId" integer NOT NULL,
    "UtilisateurId" integer NOT NULL,
    "Role" integer NOT NULL,
    "DateAjout" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_MembresListe" PRIMARY KEY ("ListeId", "UtilisateurId"),
    CONSTRAINT "CK_MembresListe_Role" CHECK ("Role" IN (1, 2, 3))
);

CREATE TABLE IF NOT EXISTS public."Classements"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ClassementPosition" integer NOT NULL,
    "Points" integer NOT NULL,
    "NiveauId" integer NOT NULL,
    "ListeId" integer NOT NULL,
    CONSTRAINT "PK_Classements" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CreateursNiveaux"
(
    "CreateurId" integer NOT NULL,
    "NiveauId" integer NOT NULL,
    CONSTRAINT "PK_CreateursNiveaux" PRIMARY KEY ("CreateurId", "NiveauId")
);

CREATE TABLE IF NOT EXISTS public."Difficultes"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Difficultes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."DiscordAccounts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DiscordId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "DiscordUsername" character varying(100) COLLATE pg_catalog."default",
    "AvatarHash" character varying(100) COLLATE pg_catalog."default",
    "UtilisateurId" integer NOT NULL,
    "DiscordDisplayName" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "DiscordAccount_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_DiscordAccounts_DiscordId" UNIQUE ("DiscordId")
);

CREATE TABLE IF NOT EXISTS public."AdminsSite"
(
    "UtilisateurId" integer NOT NULL,
    "DateAjout" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AdminsSite" PRIMARY KEY ("UtilisateurId")
);

CREATE TABLE IF NOT EXISTS public."FusionsUtilisateurs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurDemandeurId" integer NOT NULL,
    "UtilisateurCibleId" integer NOT NULL,
    "NomConserve" text COLLATE pg_catalog."default" NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    "Motif" text COLLATE pg_catalog."default",
    "DateDemande" timestamp without time zone NOT NULL DEFAULT now(),
    "DateTraitement" timestamp without time zone,
    CONSTRAINT "PK_FusionsUtilisateurs" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_FusionsUtilisateurs_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."DemandesNiveauxSupplementaires"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ListeId" integer NOT NULL,
    "UtilisateurDemandeurId" integer NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    "DateDemande" timestamp without time zone NOT NULL DEFAULT now(),
    "DateTraitement" timestamp without time zone,
    CONSTRAINT "PK_DemandesNiveauxSupplementaires" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_DemandesNiveauxSupplementaires_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."DemandesListesSupplementaires"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurId" integer NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    "DateDemande" timestamp without time zone NOT NULL DEFAULT now(),
    "DateTraitement" timestamp without time zone,
    CONSTRAINT "PK_DemandesListesSupplementaires" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_DemandesListesSupplementaires_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."Niveaux"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdDuNiveauDansLeJeu" text COLLATE pg_catalog."default" NOT NULL,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    "UrlVerification" text COLLATE pg_catalog."default" NOT NULL,
    "Duree" integer NOT NULL,
    "DateAjout" timestamp without time zone NOT NULL DEFAULT now(),
    "VerifieurId" integer NOT NULL,
    "PublisherId" integer NOT NULL,
    "RatingId" integer NOT NULL,
    "ListeId" integer NOT NULL,
    CONSTRAINT "PK_Niveaux" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ReussitesNiveaux"
(
    "UtilisateurId" integer NOT NULL,
    "NiveauId" integer NOT NULL,
    "Video" text COLLATE pg_catalog."default" NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_ReussitesNiveaux" PRIMARY KEY ("UtilisateurId", "NiveauId"),
    CONSTRAINT "CK_ReussitesNiveaux_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."SoumissionsNiveaux"
(
    "IdSoumission" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "NiveauId" integer NOT NULL,
    "UtilisateurId" integer,
    "UrlVideo" text COLLATE pg_catalog."default" NOT NULL,
    "NomUtilisateur" text COLLATE pg_catalog."default" NOT NULL,
    "RawFootageUrl" text COLLATE pg_catalog."default",
    "DateSoumission" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_SoumissionsNiveaux" PRIMARY KEY ("IdSoumission")
);

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurId" integer NOT NULL,
    "Type" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Titre" character varying(160) COLLATE pg_catalog."default" NOT NULL,
    "Message" character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    "Lien" character varying(500) COLLATE pg_catalog."default",
    "DateCreation" timestamp without time zone NOT NULL DEFAULT now(),
    "DateLecture" timestamp without time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Listes"
    ADD CONSTRAINT "FK_Listes_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Listes_UtilisateurId"
    ON public."Listes"("UtilisateurId");

ALTER TABLE IF EXISTS public."MembresListe"
    ADD CONSTRAINT "FK_MembresListe_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_MembresListe_ListeId"
    ON public."MembresListe"("ListeId");

ALTER TABLE IF EXISTS public."MembresListe"
    ADD CONSTRAINT "FK_MembresListe_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Classements"
    ADD CONSTRAINT "FK_Classements_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Classements_NiveauId"
    ON public."Classements"("NiveauId");

ALTER TABLE IF EXISTS public."Classements"
    ADD CONSTRAINT "FK_Classements_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Classements_ListeId"
    ON public."Classements"("ListeId");

ALTER TABLE IF EXISTS public."CreateursNiveaux"
    ADD CONSTRAINT "FK_CreateursNiveaux_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CreateursNiveaux_NiveauId"
    ON public."CreateursNiveaux"("NiveauId");

ALTER TABLE IF EXISTS public."CreateursNiveaux"
    ADD CONSTRAINT "FK_CreateursNiveaux_Utilisateurs_CreateurId" FOREIGN KEY ("CreateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."DiscordAccounts"
    ADD CONSTRAINT fk_discordaccount_utilisateur FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."FusionsUtilisateurs"
    ADD CONSTRAINT "FK_FusionsUtilisateurs_UtilisateurCibleId" FOREIGN KEY ("UtilisateurCibleId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."FusionsUtilisateurs"
    ADD CONSTRAINT "FK_FusionsUtilisateurs_UtilisateurDemandeurId" FOREIGN KEY ("UtilisateurDemandeurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."AdminsSite"
    ADD CONSTRAINT "FK_AdminsSite_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."DemandesNiveauxSupplementaires"
    ADD CONSTRAINT "FK_DemandesNiveauxSupplementaires_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_DemandesNiveauxSupplementaires_ListeId"
    ON public."DemandesNiveauxSupplementaires"("ListeId");

ALTER TABLE IF EXISTS public."DemandesNiveauxSupplementaires"
    ADD CONSTRAINT "FK_DemandesNiveauxSupplementaires_Utilisateurs_UtilisateurDemandeurId" FOREIGN KEY ("UtilisateurDemandeurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."DemandesListesSupplementaires"
    ADD CONSTRAINT "FK_DemandesListesSupplementaires_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Difficultes_RatingId" FOREIGN KEY ("RatingId")
    REFERENCES public."Difficultes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_RatingId"
    ON public."Niveaux"("RatingId");

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Utilisateurs_PublisherId" FOREIGN KEY ("PublisherId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_PublisherId"
    ON public."Niveaux"("PublisherId");

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Utilisateurs_VerifieurId" FOREIGN KEY ("VerifieurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_VerifieurId"
    ON public."Niveaux"("VerifieurId");

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_ListeId"
    ON public."Niveaux"("ListeId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Niveaux_Liste_IdJeu"
    ON public."Niveaux"("ListeId", "IdDuNiveauDansLeJeu");

ALTER TABLE IF EXISTS public."ReussitesNiveaux"
    ADD CONSTRAINT "FK_ReussitesNiveaux_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ReussitesNiveaux_NiveauId"
    ON public."ReussitesNiveaux"("NiveauId");

ALTER TABLE IF EXISTS public."ReussitesNiveaux"
    ADD CONSTRAINT "FK_ReussitesNiveaux_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."SoumissionsNiveaux"
    ADD CONSTRAINT "FK_SoumissionsNiveaux_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_SoumissionsNiveaux_NiveauId"
    ON public."SoumissionsNiveaux"("NiveauId");

ALTER TABLE IF EXISTS public."SoumissionsNiveaux"
    ADD CONSTRAINT "FK_SoumissionsNiveaux_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "IX_SoumissionsNiveaux_UtilisateurId"
    ON public."SoumissionsNiveaux"("UtilisateurId");

ALTER TABLE IF EXISTS public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId_DateCreation"
    ON public."Notifications"("UtilisateurId", "DateCreation" DESC);
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId_DateLecture"
    ON public."Notifications"("UtilisateurId", "DateLecture");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Classements_Liste_Position"
    ON public."Classements" ("ListeId", "ClassementPosition");

END;
