BEGIN;

CREATE TABLE IF NOT EXISTS public."Utilisateurs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    "CodePays" character varying(2) COLLATE pg_catalog."default",
    "LanguePreferee" character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Utilisateurs" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Utilisateurs_Nom" UNIQUE ("Nom"),
    CONSTRAINT "CK_Utilisateurs_CodePays" CHECK ("CodePays" IS NULL OR "CodePays" ~ '^[A-Z]{2}$'),
    CONSTRAINT "CK_Utilisateurs_LanguePreferee" CHECK ("LanguePreferee" IS NULL OR "LanguePreferee" IN ('fr', 'en', 'es'))
);

CREATE TABLE IF NOT EXISTS public."Listes"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "UtilisateurId" integer NOT NULL,
    "DateCreation" timestamp without time zone NOT NULL DEFAULT now(),
    "EstPublique" boolean NOT NULL DEFAULT true,
    "DiscordServerUrl" text COLLATE pg_catalog."default",
    "RawFootageMode" integer NOT NULL DEFAULT 0,
    "RawFootageTopStart" integer,
    "VideoToujoursRequise" boolean NOT NULL DEFAULT true,
    "VideoDifficulteMinimaleId" integer,
    "VideoTopStart" integer,
    "EstSupprimee" boolean NOT NULL DEFAULT false,
    "DateSuppression" timestamp without time zone,
    "SupprimeeParUtilisateurId" integer,
    CONSTRAINT "PK_Listes" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Listes_VideoTopStart" CHECK ("VideoTopStart" IS NULL OR "VideoTopStart" > 0),
    CONSTRAINT "CK_Listes_CritereVideo" CHECK ("VideoToujoursRequise" OR "VideoDifficulteMinimaleId" IS NOT NULL OR "VideoTopStart" IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS public."MembresListe"
(
    "ListeId" integer NOT NULL,
    "UtilisateurId" integer NOT NULL,
    "Role" integer NOT NULL,
    "DateAjout" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_MembresListe" PRIMARY KEY ("ListeId", "UtilisateurId"),
    CONSTRAINT "CK_MembresListe_Role" CHECK ("Role" IN (1, 2, 3))
);

CREATE TABLE IF NOT EXISTS public."Classements"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ClassementPosition" integer NOT NULL,
    "Points" integer NOT NULL,
    "NiveauId" integer NOT NULL,
    "ListeId" integer NOT NULL,
    CONSTRAINT "PK_Classements" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."CreateursNiveaux"
(
    "CreateurId" integer NOT NULL,
    "NiveauId" integer NOT NULL,
    CONSTRAINT "PK_CreateursNiveaux" PRIMARY KEY ("CreateurId", "NiveauId")
);

CREATE TABLE IF NOT EXISTS public."Difficultes"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Difficultes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."DiscordAccounts"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DiscordId" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "DiscordUsername" character varying(100) COLLATE pg_catalog."default",
    "AvatarHash" character varying(100) COLLATE pg_catalog."default",
    "UtilisateurId" integer NOT NULL,
    "DiscordDisplayName" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "DiscordAccount_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_DiscordAccounts_DiscordId" UNIQUE ("DiscordId")
);

CREATE TABLE IF NOT EXISTS public."AdminsSite"
(
    "UtilisateurId" integer NOT NULL,
    "DateAjout" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AdminsSite" PRIMARY KEY ("UtilisateurId")
);

CREATE TABLE IF NOT EXISTS public."FusionsUtilisateurs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurDemandeurId" integer NOT NULL,
    "UtilisateurCibleId" integer NOT NULL,
    "NomConserve" text COLLATE pg_catalog."default" NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    "Motif" text COLLATE pg_catalog."default",
    "DateDemande" timestamp without time zone NOT NULL DEFAULT now(),
    "DateTraitement" timestamp without time zone,
    CONSTRAINT "PK_FusionsUtilisateurs" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_FusionsUtilisateurs_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."DemandesNiveauxSupplementaires"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ListeId" integer NOT NULL,
    "UtilisateurDemandeurId" integer NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    "DateDemande" timestamp without time zone NOT NULL DEFAULT now(),
    "DateTraitement" timestamp without time zone,
    CONSTRAINT "PK_DemandesNiveauxSupplementaires" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_DemandesNiveauxSupplementaires_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."DemandesListesSupplementaires"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurId" integer NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    "DateDemande" timestamp without time zone NOT NULL DEFAULT now(),
    "DateTraitement" timestamp without time zone,
    CONSTRAINT "PK_DemandesListesSupplementaires" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_DemandesListesSupplementaires_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."Niveaux"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "IdDuNiveauDansLeJeu" text COLLATE pg_catalog."default" NOT NULL,
    "Nom" text COLLATE pg_catalog."default" NOT NULL,
    "UrlVerification" text COLLATE pg_catalog."default" NOT NULL,
    "Duree" integer NOT NULL,
    "DateAjout" timestamp without time zone NOT NULL DEFAULT now(),
    "VerifieurId" integer NOT NULL,
    "PublisherId" integer NOT NULL,
    "RatingId" integer NOT NULL,
    "ListeId" integer NOT NULL,
    CONSTRAINT "PK_Niveaux" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ReussitesNiveaux"
(
    "UtilisateurId" integer NOT NULL,
    "NiveauId" integer NOT NULL,
    "Video" text COLLATE pg_catalog."default" NOT NULL,
    "Statut" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_ReussitesNiveaux" PRIMARY KEY ("UtilisateurId", "NiveauId"),
    CONSTRAINT "CK_ReussitesNiveaux_Statut" CHECK ("Statut" IN ('EnAttente', 'Validee', 'Refusee'))
);

CREATE TABLE IF NOT EXISTS public."SoumissionsNiveaux"
(
    "IdSoumission" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "NiveauId" integer NOT NULL,
    "UtilisateurId" integer,
    "UrlVideo" text COLLATE pg_catalog."default" NOT NULL,
    "NomUtilisateur" text COLLATE pg_catalog."default" NOT NULL,
    "RawFootageUrl" text COLLATE pg_catalog."default",
    "DateSoumission" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_SoumissionsNiveaux" PRIMARY KEY ("IdSoumission")
);

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurId" integer NOT NULL,
    "Type" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Titre" character varying(160) COLLATE pg_catalog."default" NOT NULL,
    "Message" character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    "Lien" character varying(500) COLLATE pg_catalog."default",
    "DateCreation" timestamp without time zone NOT NULL DEFAULT now(),
    "DateLecture" timestamp without time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."HistoriquesListes"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ListeId" integer NOT NULL,
    "UtilisateurId" integer,
    "TypeAction" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(500) COLLATE pg_catalog."default" NOT NULL,
    "CleCible" character varying(100) COLLATE pg_catalog."default",
    "DonneesAvant" jsonb,
    "DonneesApres" jsonb,
    "DateCreation" timestamp without time zone NOT NULL DEFAULT now(),
    "PeutEtreAnnulee" boolean NOT NULL DEFAULT false,
    "DateAnnulation" timestamp without time zone,
    "AnnuleeParUtilisateurId" integer,
    CONSTRAINT "PK_HistoriquesListes" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public."Listes"
    ADD CONSTRAINT "FK_Listes_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Listes_UtilisateurId"
    ON public."Listes"("UtilisateurId");

ALTER TABLE IF EXISTS public."MembresListe"
    ADD CONSTRAINT "FK_MembresListe_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_MembresListe_ListeId"
    ON public."MembresListe"("ListeId");

ALTER TABLE IF EXISTS public."MembresListe"
    ADD CONSTRAINT "FK_MembresListe_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Classements"
    ADD CONSTRAINT "FK_Classements_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Classements_NiveauId"
    ON public."Classements"("NiveauId");

ALTER TABLE IF EXISTS public."Classements"
    ADD CONSTRAINT "FK_Classements_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Classements_ListeId"
    ON public."Classements"("ListeId");

ALTER TABLE IF EXISTS public."CreateursNiveaux"
    ADD CONSTRAINT "FK_CreateursNiveaux_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_CreateursNiveaux_NiveauId"
    ON public."CreateursNiveaux"("NiveauId");

ALTER TABLE IF EXISTS public."CreateursNiveaux"
    ADD CONSTRAINT "FK_CreateursNiveaux_Utilisateurs_CreateurId" FOREIGN KEY ("CreateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."DiscordAccounts"
    ADD CONSTRAINT fk_discordaccount_utilisateur FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."FusionsUtilisateurs"
    ADD CONSTRAINT "FK_FusionsUtilisateurs_UtilisateurCibleId" FOREIGN KEY ("UtilisateurCibleId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."FusionsUtilisateurs"
    ADD CONSTRAINT "FK_FusionsUtilisateurs_UtilisateurDemandeurId" FOREIGN KEY ("UtilisateurDemandeurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."AdminsSite"
    ADD CONSTRAINT "FK_AdminsSite_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."DemandesNiveauxSupplementaires"
    ADD CONSTRAINT "FK_DemandesNiveauxSupplementaires_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_DemandesNiveauxSupplementaires_ListeId"
    ON public."DemandesNiveauxSupplementaires"("ListeId");

ALTER TABLE IF EXISTS public."DemandesNiveauxSupplementaires"
    ADD CONSTRAINT "FK_DemandesNiveauxSupplementaires_Utilisateurs_UtilisateurDemandeurId" FOREIGN KEY ("UtilisateurDemandeurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."DemandesListesSupplementaires"
    ADD CONSTRAINT "FK_DemandesListesSupplementaires_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Difficultes_RatingId" FOREIGN KEY ("RatingId")
    REFERENCES public."Difficultes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_RatingId"
    ON public."Niveaux"("RatingId");

ALTER TABLE IF EXISTS public."Listes"
    ADD CONSTRAINT "FK_Listes_Difficultes_VideoDifficulteMinimaleId" FOREIGN KEY ("VideoDifficulteMinimaleId")
    REFERENCES public."Difficultes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "IX_Listes_VideoDifficulteMinimaleId"
    ON public."Listes"("VideoDifficulteMinimaleId");

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Utilisateurs_PublisherId" FOREIGN KEY ("PublisherId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_PublisherId"
    ON public."Niveaux"("PublisherId");

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Utilisateurs_VerifieurId" FOREIGN KEY ("VerifieurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_VerifieurId"
    ON public."Niveaux"("VerifieurId");

ALTER TABLE IF EXISTS public."Niveaux"
    ADD CONSTRAINT "FK_Niveaux_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Niveaux_ListeId"
    ON public."Niveaux"("ListeId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Niveaux_Liste_IdJeu"
    ON public."Niveaux"("ListeId", "IdDuNiveauDansLeJeu");

ALTER TABLE IF EXISTS public."ReussitesNiveaux"
    ADD CONSTRAINT "FK_ReussitesNiveaux_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_ReussitesNiveaux_NiveauId"
    ON public."ReussitesNiveaux"("NiveauId");

ALTER TABLE IF EXISTS public."ReussitesNiveaux"
    ADD CONSTRAINT "FK_ReussitesNiveaux_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;

ALTER TABLE IF EXISTS public."SoumissionsNiveaux"
    ADD CONSTRAINT "FK_SoumissionsNiveaux_Niveaux_NiveauId" FOREIGN KEY ("NiveauId")
    REFERENCES public."Niveaux" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_SoumissionsNiveaux_NiveauId"
    ON public."SoumissionsNiveaux"("NiveauId");

ALTER TABLE IF EXISTS public."SoumissionsNiveaux"
    ADD CONSTRAINT "FK_SoumissionsNiveaux_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS "IX_SoumissionsNiveaux_UtilisateurId"
    ON public."SoumissionsNiveaux"("UtilisateurId");

ALTER TABLE IF EXISTS public."Notifications"
    ADD CONSTRAINT "FK_Notifications_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId_DateCreation"
    ON public."Notifications"("UtilisateurId", "DateCreation" DESC);
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId_DateLecture"
    ON public."Notifications"("UtilisateurId", "DateLecture");

ALTER TABLE IF EXISTS public."HistoriquesListes"
    ADD CONSTRAINT "FK_HistoriquesListes_Listes_ListeId" FOREIGN KEY ("ListeId")
    REFERENCES public."Listes" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

ALTER TABLE IF EXISTS public."HistoriquesListes"
    ADD CONSTRAINT "FK_HistoriquesListes_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

ALTER TABLE IF EXISTS public."HistoriquesListes"
    ADD CONSTRAINT "FK_HistoriquesListes_Utilisateurs_AnnuleeParUtilisateurId" FOREIGN KEY ("AnnuleeParUtilisateurId")
    REFERENCES public."Utilisateurs" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "IX_HistoriquesListes_ListeId_DateCreation"
    ON public."HistoriquesListes"("ListeId", "DateCreation");
CREATE INDEX IF NOT EXISTS "IX_HistoriquesListes_ListeId_CleCible_Id"
    ON public."HistoriquesListes"("ListeId", "CleCible", "Id");
CREATE INDEX IF NOT EXISTS "IX_HistoriquesListes_UtilisateurId"
    ON public."HistoriquesListes"("UtilisateurId");
CREATE INDEX IF NOT EXISTS "IX_HistoriquesListes_AnnuleeParUtilisateurId"
    ON public."HistoriquesListes"("AnnuleeParUtilisateurId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Classements_Liste_Position"
    ON public."Classements" ("ListeId", "ClassementPosition");

END;

BEGIN;

INSERT INTO public."Difficultes" ("Nom") VALUES
    ('N/A'),

    ('Auto'),
    ('Auto Featured'),
    ('Auto Epic'),
    ('Auto Legendary'),
    ('Auto Mythic'),

    ('Easy'),
    ('Easy Featured'),
    ('Easy Epic'),
    ('Easy Legendary'),
    ('Easy Mythic'),

    ('Normal'),
    ('Normal Featured'),
    ('Normal Epic'),
    ('Normal Legendary'),
    ('Normal Mythic'),

    ('Hard'),
    ('Hard Featured'),
    ('Hard Epic'),
    ('Hard Legendary'),
    ('Hard Mythic'),

    ('Harder'),
    ('Harder Featured'),
    ('Harder Epic'),
    ('Harder Legendary'),
    ('Harder Mythic'),

    ('Insane'),
    ('Insane Featured'),
    ('Insane Epic'),
    ('Insane Legendary'),
    ('Insane Mythic'),

    ('Easy Demon'),
    ('Easy Demon Featured'),
    ('Easy Demon Epic'),
    ('Easy Demon Legendary'),
    ('Easy Demon Mythic'),

    ('Medium Demon'),
    ('Medium Demon Featured'),
    ('Medium Demon Epic'),
    ('Medium Demon Legendary'),
    ('Medium Demon Mythic'),

    ('Hard Demon'),
    ('Hard Demon Featured'),
    ('Hard Demon Epic'),
    ('Hard Demon Legendary'),
    ('Hard Demon Mythic'),

    ('Insane Demon'),
    ('Insane Demon Featured'),
    ('Insane Demon Epic'),
    ('Insane Demon Legendary'),
    ('Insane Demon Mythic'),

    ('Extreme Demon'),
    ('Extreme Demon Featured'),
    ('Extreme Demon Epic'),
    ('Extreme Demon Legendary'),
    ('Extreme Demon Mythic');

END;
