BEGIN;

ALTER TABLE public."SoumissionsNiveaux"
    ADD COLUMN IF NOT EXISTS "UtilisateurId" integer;

CREATE TABLE IF NOT EXISTS public."Notifications"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UtilisateurId" integer NOT NULL,
    "Type" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Titre" character varying(160) COLLATE pg_catalog."default" NOT NULL,
    "Message" character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    "Lien" character varying(500) COLLATE pg_catalog."default",
    "DateCreation" timestamp without time zone NOT NULL DEFAULT now(),
    "DateLecture" timestamp without time zone,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_SoumissionsNiveaux_Utilisateurs_UtilisateurId'
    ) THEN
        ALTER TABLE public."SoumissionsNiveaux"
            ADD CONSTRAINT "FK_SoumissionsNiveaux_Utilisateurs_UtilisateurId"
            FOREIGN KEY ("UtilisateurId") REFERENCES public."Utilisateurs" ("Id") ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Notifications_Utilisateurs_UtilisateurId'
    ) THEN
        ALTER TABLE public."Notifications"
            ADD CONSTRAINT "FK_Notifications_Utilisateurs_UtilisateurId"
            FOREIGN KEY ("UtilisateurId") REFERENCES public."Utilisateurs" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_SoumissionsNiveaux_UtilisateurId"
    ON public."SoumissionsNiveaux"("UtilisateurId");
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId_DateCreation"
    ON public."Notifications"("UtilisateurId", "DateCreation" DESC);
CREATE INDEX IF NOT EXISTS "IX_Notifications_UtilisateurId_DateLecture"
    ON public."Notifications"("UtilisateurId", "DateLecture");

COMMIT;
