services:
  db:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Sql/01-Init.sql:/docker-entrypoint-initdb.d/01-Init.sql:ro
      - ./Sql/02-SeedDev.sql:/docker-entrypoint-initdb.d/02-SeedDev.sql:ro
    ports:
      - "21555:5432"
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
